""" dropped SongData.id

Revision ID: 1f048a70bb89
Revises: f50abd2a8817
Create Date: 2021-12-16 18:35:45.484377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f048a70bb89'
down_revision = 'f50abd2a8817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_data', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
