"""association table for  user follow songs

Revision ID: 537e5c876e25
Revises: ddcf1fceb47b
Create Date: 2021-12-16 20:05:07.501312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537e5c876e25'
down_revision = 'ddcf1fceb47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listeners',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listeners')
    # ### end Alembic commands ###
