"""added pop

Revision ID: 749e00129fa0
Revises: 024e9b9c3fad
Create Date: 2021-12-15 18:43:35.862778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749e00129fa0'
down_revision = '024e9b9c3fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('popularity')

    # ### end Alembic commands ###
