"""songs table

Revision ID: 946fc5eb5c3f
Revises: 7c4d33b2f0d6
Create Date: 2021-12-15 17:30:52.818293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946fc5eb5c3f'
down_revision = '7c4d33b2f0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(length=128), nullable=True),
    sa.Column('artist_name', sa.String(length=64), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('beats_per_minute', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('popularity'),
    sa.UniqueConstraint('track_name')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_table('song')
    # ### end Alembic commands ###
