"""songs pop

Revision ID: 96b51e781b64
Revises: 946fc5eb5c3f
Create Date: 2021-12-15 18:00:21.901514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b51e781b64'
down_revision = '946fc5eb5c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'popularity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('popularity', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
