"""empty message

Revision ID: aad9aa4d3da8
Revises: 96b51e781b64
Create Date: 2021-12-15 18:04:18.647307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad9aa4d3da8'
down_revision = '96b51e781b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'popularity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('popularity', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
