"""altered pop

Revision ID: ab144eea6fd2
Revises: fc94501c7b96
Create Date: 2021-12-16 17:30:57.010458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab144eea6fd2'
down_revision = 'fc94501c7b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('popularity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
