"""corrected typo and added __repr__

Revision ID: ddcf1fceb47b
Revises: 1f048a70bb89
Create Date: 2021-12-16 18:49:02.342157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddcf1fceb47b'
down_revision = '1f048a70bb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loudness_dB', sa.Integer(), nullable=True))
        batch_op.drop_column('loundness_dB')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loundness_dB', sa.INTEGER(), nullable=True))
        batch_op.drop_column('loudness_dB')

    # ### end Alembic commands ###
