"""added Second table Song data

Revision ID: f50abd2a8817
Revises: ab144eea6fd2
Create Date: 2021-12-16 18:28:43.110236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50abd2a8817'
down_revision = 'ab144eea6fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('danceability', sa.Integer(), nullable=True),
    sa.Column('loundness_dB', sa.Integer(), nullable=True),
    sa.Column('valence', sa.Integer(), nullable=True),
    sa.Column('acousticness', sa.Integer(), nullable=True),
    sa.Column('speechiness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_data')
    # ### end Alembic commands ###
